name: Snyk vulnerability reports manual

on:
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Scan vulnerabilities with snyk
      run: |
        cd scan-prj
        bash build-pom.sh
        npm install snyk -g
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk test >> snyk-results.txt || true
        cat snyk-results.txt
        echo ""
        echo ""
        echo "starting report"
        echo ""
        echo ""
        LINE_NUM=1
        while read LINE
        do
          if [[ $LINE == ✗* ]]
          then
            echo "Vulnerability: ${LINE}"
          elif [[ $LINE == Upgrade* ]]
          then
            echo "Information on how to fix it: ${LINE}"
          elif [[ $LINE == "Issues with no direct upgrade"* ]]
          then
            echo "No direct upgrade: ${LINE}"
          elif [[ $LINE == "No upgrade or patch available"* ]]
          then
            echo "No fix: ${LINE}"
          elif [[ $LINE == "This issue was fixed in versions"* ]]
          then
            echo "Explicity fix: ${LINE}"
          else
            echo "Ignored: ${LINE}"
          fi
          ((LINE_NUM++))
        done < snyk-results.txt