name: Snyk vulnerability reports manual

on:
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: pwd
      run: |
        set -xv
        pwd
        cd scan-prj
        pwd
        sh build.sh
        snyk test
        set +xv