name: Snyk vulnerability reports

on:
  schedule:
    - cron: "0 0/8 * * *"
    
jobs:
  test:
    name: Release operator-bundle
    runs-on: ubuntu-latest
    steps:
    
    - name: test
      run: |
        echo "Test"