name: Snyk vulnerability reports

on:
  schedule:
    - cron: '6 * * * *'
    
jobs:
  test:
    name: Release operator-bundle
    runs-on: ubuntu-latest
    steps:
    
    - name: test
      run: |
        echo "Test"